### ISSUE TITLE
Is this a typo ? otherwise can you pls explain

### ISSUE THREAD

**Issue by htso** [JEddy92/TimeSeries_Seq2Seq#8]
In the two notebooks Conv_Full and Conv_Full_Exog, go to the code block where you define your model (right aft 3. Building the Model - Architecture), you have the following lines,

    z = Conv1D(16, 1, padding='same', activation='relu')(z) 
    x = Add()([x, z])    
    skips.append(z)

Should the middle line be,

    z = Conv1D(16, 1, padding='same', activation='relu')(z) 
    z = Add()([x, z])    
    skips.append(z)

That is, the result of Add() is sent back to z, and get appended to skips.

**Comment by lzhang12** [comment]
Hi @htso,

I think the original implementation is correct. If you follow the figure of the WaveNet architecture, i.e., Fig 4 in the notebooks you mention, the variable passed to the skipped connections (`z`) are before the element-wise plus, so the result of Add() should not send back to `z`, but `x`.

**Comment by htso** [comment]
i've figured that out. but results not much different. thanks though.
